import { Router } from "express";
import { requireAuth } from "../../middlewares/auth.middleware.js";
import { requirePermission } from "../../middlewares/authorization.middleware.js";
import { validate } from "../../middlewares/validate.middleware.js";
import { permissions } from "../../auth/authorization.js";
import { imageUpload } from "../upload/upload.middleware.js";
import * as c from "./controllers/popup.controller.js";
import * as v from "./validations/popup.validation.js";
const router = Router();
router.get("/public", c.publicList);
router.use(requireAuth);
router.get("/", validate(v.popupListQuerySchema), requirePermission(permissions.popupsReadAny), c.list);
router.get("/:id", validate(v.popupIdSchema), requirePermission(permissions.popupsReadAny), c.get);
router.post("/", validate(v.createPopupSchema), requirePermission(permissions.popupsManage), c.create);
router.patch("/:id", validate(v.updatePopupSchema), requirePermission(permissions.popupsManage), c.update);
router.patch("/:id/status", validate(v.popupStatusSchema), requirePermission(permissions.popupsManage), c.status);
router.post("/:id/image", validate(v.popupIdSchema), imageUpload.single("image"), requirePermission(permissions.popupsManage), c.uploadImage);
router.delete("/:id", validate(v.popupIdSchema), requirePermission(permissions.popupsManage), c.remove);
export default router;
