import { Router } from "express";
import { requireAuth } from "../../middlewares/auth.middleware.js";
import { requirePermission } from "../../middlewares/authorization.middleware.js";
import { validate } from "../../middlewares/validate.middleware.js";
import { permissions } from "../../auth/authorization.js";
import { imageUpload } from "../upload/upload.middleware.js";
import * as c from "./controllers/slider.controller.js";
import * as v from "./validations/slider.validation.js";
const router = Router();
router.get("/public", c.publicList);
router.use(requireAuth);
router.get("/", validate(v.sliderListQuerySchema), requirePermission(permissions.slidersReadAny), c.list);
router.get("/:id", validate(v.sliderIdSchema), requirePermission(permissions.slidersReadAny), c.get);
router.post("/", validate(v.createSliderSchema), requirePermission(permissions.slidersManage), c.create);
router.patch("/:id", validate(v.updateSliderSchema), requirePermission(permissions.slidersManage), c.update);
router.patch("/:id/status", validate(v.sliderStatusSchema), requirePermission(permissions.slidersManage), c.status);
router.patch("/:id/reorder", validate(v.sliderReorderSchema), requirePermission(permissions.slidersManage), c.reorder);
router.post("/:id/image", validate(v.sliderIdSchema), imageUpload.single("image"), requirePermission(permissions.slidersManage), c.uploadImage);
router.post("/:id/mobile-image", validate(v.sliderIdSchema), imageUpload.single("image"), requirePermission(permissions.slidersManage), c.uploadMobileImage);
router.delete("/:id", validate(v.sliderIdSchema), requirePermission(permissions.slidersManage), c.remove);
export default router;
