import type { Request, Response } from "express";
import { asyncHandler } from "../../../utils/asyncHandler.js";
import { paginatedResponse, successResponse } from "../../../utils/api-response.js";
import { NotFoundError } from "../../../errors/AppError.js";
import { ConflictError } from "../../../errors/AppError.js";
import * as shipmentRepo from "../../shipment/repositories/shipment.repository.js";
import * as service from "../services/order.service.js";
import type { OrderListQuery, OrderTransitionInput } from "../order.types.js";
export const list = asyncHandler(async (req: Request, res: Response) => { const q = req.query as unknown as OrderListQuery; const rows = await service.customerList(req.auth!.userId, q); res.json(paginatedResponse("Orders fetched successfully", rows as any[], { page: q.page, limit: q.limit, total: rows.length, totalPages: rows.length === q.limit ? q.page + 1 : q.page })); });
export const adminList = asyncHandler(async (req: Request, res: Response) => { const q = req.query as unknown as OrderListQuery; const rows = await service.adminList(q); res.json(paginatedResponse("Orders fetched successfully", rows as any[], { page: q.page, limit: q.limit, total: rows.length, totalPages: rows.length === q.limit ? q.page + 1 : q.page })); });
export const detail = asyncHandler(async (req: Request, res: Response) => res.json(successResponse("Order fetched successfully", await service.detail(String(req.params.orderNumber), req.auth!.userId))));
export const guestDetail = asyncHandler(async (req: Request, res: Response) => res.json(successResponse("Order fetched successfully", await service.detail(String(req.params.orderNumber), undefined, String(req.query.accessToken ?? "")))));
export const adminDetail = asyncHandler(async (req: Request, res: Response) => { const x: any = await (await import("../repositories/order.repository.js")).findByNumber(String(req.params.orderNumber)); if (!x) throw new NotFoundError("Order not found"); res.json(successResponse("Order fetched successfully", x)); });
export const transition = asyncHandler(async (req: Request, res: Response) => { const body = req.body as OrderTransitionInput; if (body.status === "SHIPPED" && await shipmentRepo.findByOrderNumber(String(req.params.orderNumber))) throw new ConflictError("Shipment workflow is required to ship this order"); res.json(successResponse("Order status updated successfully", await service.transition(String(req.params.orderNumber), body.status, req.auth!.userId, body.note))); });
