import { db } from "../../../prisma/db.js";
export const addresses = (userId: number) => db.orm.public.Address.select("id", "label", "fullName", "phone", "addressLine1", "addressLine2", "division", "district", "upazila", "thana", "area", "postalCode", "countryCode", "isDefaultShipping", "isDefaultBilling", "createdAt", "updatedAt").where({ userId }).all();
export const address = (userId: number, id: number) => db.orm.public.Address.select("id", "label", "fullName", "phone", "addressLine1", "addressLine2", "division", "district", "upazila", "thana", "area", "postalCode", "countryCode", "isDefaultShipping", "isDefaultBilling", "createdAt", "updatedAt").first({ userId, id });
export const createAddress = (tx: any, userId: number, data: any) => tx.orm.public.Address.select("id", "label", "fullName", "phone", "addressLine1", "addressLine2", "division", "district", "upazila", "thana", "area", "postalCode", "countryCode", "isDefaultShipping", "isDefaultBilling", "createdAt", "updatedAt").create({ userId, ...data });
export const updateAddress = (tx: any, id: number, data: any) => tx.orm.public.Address.where({ id }).select("id", "label", "fullName", "phone", "addressLine1", "addressLine2", "division", "district", "upazila", "thana", "area", "postalCode", "countryCode", "isDefaultShipping", "isDefaultBilling", "createdAt", "updatedAt").update(data);
export const clearDefaults = (tx: any, userId: number, field: "isDefaultShipping" | "isDefaultBilling") => tx.orm.public.Address.where({ userId }).select("id").update({ [field]: false });
export const removeAddress = (tx: any, id: number) => tx.orm.public.Address.where({ id }).delete();
export const zones = () => db.orm.public.ShippingZone.select("id", "name", "description", "isActive", "sortOrder", "createdAt", "updatedAt").orderBy([(z: any) => z.sortOrder.asc(), (z: any) => z.id.asc()]).all();
export const zone = (id: number) => db.orm.public.ShippingZone.select("id", "name", "description", "isActive", "sortOrder", "createdAt", "updatedAt").first({ id });
export const createZone = (data: any) => db.orm.public.ShippingZone.select("id", "name", "description", "isActive", "sortOrder", "createdAt", "updatedAt").create(data);
export const updateZone = (id: number, data: any) => db.orm.public.ShippingZone.where({ id }).select("id", "name", "description", "isActive", "sortOrder", "createdAt", "updatedAt").update(data);
export const deleteZone = (id: number) => db.orm.public.ShippingZone.where({ id }).delete();
export const areas = (zoneId: number) => db.orm.public.ShippingZoneArea.select("id", "zoneId", "countryCode", "division", "district", "upazila", "thana", "area", "postalCode").where({ zoneId }).all();
export const createArea = (data: any) => db.orm.public.ShippingZoneArea.create(data);
export const updateArea = (id: number, data: any) => db.orm.public.ShippingZoneArea.where({ id }).update(data);
export const deleteArea = (id: number) => db.orm.public.ShippingZoneArea.where({ id }).delete();
export const methods = () => db.orm.public.ShippingMethod.select("id", "name", "code", "description", "isActive", "sortOrder").orderBy([(m: any) => m.sortOrder.asc(), (m: any) => m.id.asc()]).all();
export const method = (id: number) => db.orm.public.ShippingMethod.select("id", "name", "code", "description", "isActive", "sortOrder").first({ id });
export const createMethod = (data: any) => db.orm.public.ShippingMethod.create(data);
export const updateMethod = (id: number, data: any) => db.orm.public.ShippingMethod.where({ id }).update(data);
export const deleteMethod = (id: number) => db.orm.public.ShippingMethod.where({ id }).delete();
export const matchingAreas = () => db.orm.public.ShippingZoneArea.select("id", "zoneId", "countryCode", "division", "district", "upazila", "thana", "area", "postalCode").include("zone", (z: any) => z.select("id", "name", "isActive")).all();
export const zoneOptions = (zoneId: number) => db.orm.public.ShippingZoneMethod.select("id", "zoneId", "methodId", "charge", "estimatedMinDays", "estimatedMaxDays", "isActive", "sortOrder").where({ zoneId, isActive: true }).include("method", (m: any) => m.select("id", "name", "code", "description", "isActive")).orderBy([(x: any) => x.sortOrder.asc(), (x: any) => x.id.asc()]).all();
export const createZoneMethod = (data: any) => db.orm.public.ShippingZoneMethod.create(data);
