import { Router } from "express";
import { requireAuth } from "../../middlewares/auth.middleware.js";
import { requirePermission } from "../../middlewares/authorization.middleware.js";
import { validate } from "../../middlewares/validate.middleware.js";
import { permissions } from "../../auth/authorization.js";
import * as c from "./controllers/navigation.controller.js";
import * as v from "./validations/navigation.validation.js";

const router = Router();
router.get("/public/:key", c.publicMenu);
router.use(requireAuth);
router.get("/", requirePermission(permissions.navigationReadAny), c.listMenus);
router.post("/", validate(v.createMenuSchema), requirePermission(permissions.navigationManage), c.createMenu);
router.get("/:menuId", validate(v.menuIdSchema), requirePermission(permissions.navigationReadAny), c.getMenu);
router.patch("/:menuId", validate(v.updateMenuSchema), requirePermission(permissions.navigationManage), c.updateMenu);
router.delete("/:menuId", validate(v.menuIdSchema), requirePermission(permissions.navigationManage), c.removeMenu);
router.get("/:menuId/items", validate(v.menuIdSchema), requirePermission(permissions.navigationReadAny), c.listItems);
router.post("/:menuId/items", validate(v.createItemSchema), requirePermission(permissions.navigationManage), c.createItem);
router.patch("/:menuId/items/:itemId", validate(v.updateItemSchema), requirePermission(permissions.navigationManage), c.updateItem);
router.delete("/:menuId/items/:itemId", validate(v.itemIdSchema), requirePermission(permissions.navigationManage), c.removeItem);
router.get("/:menuId/items/:itemId/sections", validate(v.itemIdSchema), requirePermission(permissions.navigationReadAny), c.listSections);
router.post("/:menuId/items/:itemId/sections", validate(v.createSectionSchema), requirePermission(permissions.navigationManage), c.createSection);
router.patch("/:menuId/items/:itemId/sections/:sectionId", validate(v.updateSectionSchema), requirePermission(permissions.navigationManage), c.updateSection);
router.delete("/:menuId/items/:itemId/sections/:sectionId", validate(v.sectionIdSchema), requirePermission(permissions.navigationManage), c.removeSection);
router.get("/:menuId/items/:itemId/sections/:sectionId/entries", validate(v.sectionIdSchema), requirePermission(permissions.navigationReadAny), c.listEntries);
router.post("/:menuId/items/:itemId/sections/:sectionId/entries", validate(v.createEntrySchema), requirePermission(permissions.navigationManage), c.createEntry);
router.patch("/:menuId/items/:itemId/sections/:sectionId/entries/:entryId", validate(v.updateEntrySchema), requirePermission(permissions.navigationManage), c.updateEntry);
router.delete("/:menuId/items/:itemId/sections/:sectionId/entries/:entryId", validate(v.entryIdSchema), requirePermission(permissions.navigationManage), c.removeEntry);
export default router;
