import { z } from "zod";
const id = z.coerce.number().int().positive();
const location = z.string().trim().max(120).nullable().optional();
export const addressId = z.object({ params: z.object({ addressId: id }) });
const addressFields = { label: z.string().trim().max(80).nullable().optional(), fullName: z.string().trim().min(2).max(150), phone: z.string().trim().min(7).max(30), addressLine1: z.string().trim().min(3).max(250), addressLine2: z.string().trim().max(250).nullable().optional(), division: location, district: z.string().trim().min(2).max(120), upazila: location, thana: location, area: location, postalCode: z.string().trim().max(20).nullable().optional(), countryCode: z.string().trim().length(2).default("BD") };
export const createAddress = z.object({ body: z.object({ ...addressFields, isDefaultShipping: z.boolean().optional(), isDefaultBilling: z.boolean().optional() }).strict() });
export const updateAddress = z.object({ params: z.object({ addressId: id }), body: z.object({ ...addressFields, isDefaultShipping: z.boolean().optional(), isDefaultBilling: z.boolean().optional() }).partial().strict().refine((x) => Object.keys(x).length > 0, "At least one field is required") });
export const zoneId = z.object({ params: z.object({ zoneId: id }) });
export const zoneAreaId = z.object({ params: z.object({ zoneId: id, areaId: id }) });
export const zoneBody = z.object({ body: z.object({ name: z.string().trim().min(1).max(150), description: z.string().trim().max(500).nullable().optional(), isActive: z.boolean().optional(), sortOrder: z.coerce.number().int().min(0).optional() }).strict() });
export const areaBody = z.object({ params: z.object({ zoneId: id }), body: z.object({ countryCode: z.string().trim().length(2).default("BD"), division: location, district: location, upazila: location, thana: location, area: location, postalCode: location }).strict() });
export const areaUpdate = z.object({ params: z.object({ zoneId: id, areaId: id }), body: areaBody.shape.body.partial().strict() });
export const methodBody = z.object({ body: z.object({ name: z.string().trim().min(1).max(150), code: z.string().trim().min(1).max(50), description: z.string().trim().max(500).nullable().optional(), isActive: z.boolean().optional(), sortOrder: z.coerce.number().int().min(0).optional() }).strict() });
export const methodId = z.object({ params: z.object({ methodId: id }) });
export const optionQuery = z.object({ query: z.object({ addressId: id }).strict() });
export const zoneMethodBody = z.object({ params: z.object({ zoneId: id }), body: z.object({ methodId: id, charge: z.coerce.number().min(0), estimatedMinDays: z.coerce.number().int().min(0).nullable().optional(), estimatedMaxDays: z.coerce.number().int().min(0).nullable().optional(), isActive: z.boolean().optional(), sortOrder: z.coerce.number().int().min(0).optional() }).strict().superRefine((v, ctx) => { if (v.estimatedMinDays != null && v.estimatedMaxDays != null && v.estimatedMaxDays < v.estimatedMinDays) ctx.addIssue({ code: "custom", message: "estimatedMaxDays must be >= estimatedMinDays" }); }) });
