import { asyncHandler } from "../../../utils/asyncHandler.js";
import { successResponse } from "../../../utils/api-response.js";
import * as s from "../services/shipping.service.js";
export const addresses = asyncHandler(async (req, res) => res.json(successResponse("Addresses fetched successfully", await s.listAddresses(req.auth!.userId))));
export const address = asyncHandler(async (req, res) => res.json(successResponse("Address fetched successfully", await s.getAddress(req.auth!.userId, Number(req.params.addressId)))));
export const createAddress = asyncHandler(async (req, res) => res.status(201).json(successResponse("Address created successfully", await s.createAddress(req.auth!.userId, req.body))));
export const updateAddress = asyncHandler(async (req, res) => res.json(successResponse("Address updated successfully", await s.updateAddress(req.auth!.userId, Number(req.params.addressId), req.body))));
export const deleteAddress = asyncHandler(async (req, res) => { await s.deleteAddress(req.auth!.userId, Number(req.params.addressId)); res.json(successResponse("Address deleted successfully", null)); });
export const defaultShipping = asyncHandler(async (req, res) => res.json(successResponse("Default shipping address updated successfully", await s.setDefault(req.auth!.userId, Number(req.params.addressId), "isDefaultShipping"))));
export const defaultBilling = asyncHandler(async (req, res) => res.json(successResponse("Default billing address updated successfully", await s.setDefault(req.auth!.userId, Number(req.params.addressId), "isDefaultBilling"))));
export const zones = asyncHandler(async (_req, res) => res.json(successResponse("Shipping zones fetched successfully", await s.listZones())));
export const zone = asyncHandler(async (req, res) => res.json(successResponse("Shipping zone fetched successfully", await s.getZone(Number(req.params.zoneId)))));
export const createZone = asyncHandler(async (req, res) => res.status(201).json(successResponse("Shipping zone created successfully", await s.createZone(req.body))));
export const updateZone = asyncHandler(async (req, res) => res.json(successResponse("Shipping zone updated successfully", await s.updateZone(Number(req.params.zoneId), req.body))));
export const deleteZone = asyncHandler(async (req, res) => { await s.deleteZone(Number(req.params.zoneId)); res.json(successResponse("Shipping zone deleted successfully", null)); });
export const areas = asyncHandler(async (req, res) => res.json(successResponse("Shipping areas fetched successfully", await s.listAreas(Number(req.params.zoneId)))));
export const createArea = asyncHandler(async (req, res) => res.status(201).json(successResponse("Shipping area created successfully", await s.createArea(Number(req.params.zoneId), req.body))));
export const updateArea = asyncHandler(async (req, res) => res.json(successResponse("Shipping area updated successfully", await s.updateArea(Number(req.params.zoneId), Number(req.params.areaId), req.body))));
export const deleteArea = asyncHandler(async (req, res) => { await s.deleteArea(Number(req.params.zoneId), Number(req.params.areaId)); res.json(successResponse("Shipping area deleted successfully", null)); });
export const methods = asyncHandler(async (_req, res) => res.json(successResponse("Shipping methods fetched successfully", await s.listMethods())));
export const method = asyncHandler(async (req, res) => res.json(successResponse("Shipping method fetched successfully", await s.getMethod(Number(req.params.methodId)))));
export const createMethod = asyncHandler(async (req, res) => res.status(201).json(successResponse("Shipping method created successfully", await s.createMethod(req.body))));
export const updateMethod = asyncHandler(async (req, res) => res.json(successResponse("Shipping method updated successfully", await s.updateMethod(Number(req.params.methodId), req.body))));
export const deleteMethod = asyncHandler(async (req, res) => { await s.deleteMethod(Number(req.params.methodId)); res.json(successResponse("Shipping method deleted successfully", null)); });
export const options = asyncHandler(async (req, res) => res.json(successResponse("Shipping options fetched successfully", await s.options(req.auth!.userId, Number(req.query.addressId)))));
export const createZoneMethod = asyncHandler(async (req, res) => res.status(201).json(successResponse("Shipping zone method created successfully", await s.createZoneMethod(Number(req.params.zoneId), req.body))));
